# Generated by Django 4.2.7 on 2023-12-03 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images')),
                ('image_frame', models.PositiveIntegerField(choices=[(1, 'Top rounded'), (2, 'Top right and bottom left rounded'), (3, 'Full rounded'), (4, 'Bottom rounded'), (5, 'Bottom right rounded')], verbose_name='Image Frame Style')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('post_commentary', models.TextField(max_length=1200, verbose_name='Commentary')),
                ('approved', models.BooleanField(default=False, verbose_name='Post Approved?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostCommentaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentary', models.TextField(max_length=1200, verbose_name='Commentary')),
                ('favorite', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery.usersposts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
