# Generated by Django 4.2.7 on 2023-12-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersposts',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active ?'),
        ),
    ]
