# Generated by Django 4.2.7 on 2023-12-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0004_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_right',
            field=models.BooleanField(default=False),
        ),
    ]
